#!/bin/bash
# postinst script for geonode
#
# see: dh_installdeb(1)

. /usr/share/debconf/confmodule

# Setup tomcat startup options
cat >> /etc/default/tomcat6 <<- EOF 
JAVA_OPTS='-Djava.awt.headless=true -Xmx1024m -Xms1024M -XX:MaxPermSize=256m -XX:CompileCommand=exclude,net/sf/saxon/event/ReceivingContentHandler.startElement'
EOF

ln -sf /etc/geonode/geonetwork/config.xml /var/lib/tomcat6/webapps/geonetwork/WEB-INF

service tomcat6 restart