#!/bin/bash
if [ $1 = 0 ]; then
  service tomcat9 stop > /dev/null 2>&1
  if [ -f /sbin/chkconfig ]; then
    chkconfig --del tomcat9
  elif [ -f /usr/sbin/update-rc.d ]; then
    update-rc.d -f tomcat9 remove
    unlink /etc/init.d/tomcat9
  fi
fi
