#!/bin/bash

function usage() {
  echo "Usage: opengeo-suite <start|stop>"
}

if [ "$1" == "" ]; then
  usage
  exit
fi

pushd "`dirname "$0"`" > /dev/null
dir=`pwd`
 
if [ ! -e "$dir/og-jetty.jar" ]; then
  echo "Could not find og-jetty.jar"
  exit -1
fi

_RUNJAVA=""
if [ -e "$dir/jre" ]; then
  _RUNJAVA="$dir/jre/bin/java"
else
  if [ "$JAVA_HOME" != "" ] && [ -e $JAVA_HOME/bin/java ]; then
    _RUNJAVA=$JAVA_HOME/bin/java
  else
    which java > /dev/null
    if [ "$?" == "1" ]; then
      echo "JAVA_HOME is not defined, and java is not on the current PATH"
      exit
    fi
    _RUNJAVA=`which java`
  fi
fi

CLASSPATH=og-jetty.jar:jetty-start.jar:lib/ini4j-0.5.1.jar:lib/log4j-1.2.14.jar:lib/commons-logging-1.0.jar:lib/slf4j-jcl-1.0.1.jar
VMOPTS="-Xms128m -Xmx512m -XX:MaxPermSize=256m"
OPTS="-Djava.awt.headless=true -Dslf4j=false -cp $CLASSPATH -Djava.library.path=$dir/../lib -Dorg.geotools.referencing.forceXY=true"

base=$dir/../
export DYLD_LIBRARY_PATH=$base/lib
export GDAL_DRIVER_PATH=$base/lib/gdalplugins
export GDAL_DATA=$base/share/gdal

case "$1" in

  start)
    exec "$_RUNJAVA" $VMOPTS $OPTS org.opengeo.jetty.Start
    ;;

  stop)
    exec "$_RUNJAVA" $VMOPTS $OPTS org.opengeo.jetty.Start --stop
    ;;
   
  *)
    usage
esac

popd > /dev/null
